# Generated by Django 6.1 on 2026-08-31 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertdismissal',
            unique_together={('report', 'approver')},
        ),
        migrations.AddField(
            model_name='alertdismissal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertdismissal',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertdismissal',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='expenses.expensereport'),
        ),
        migrations.RemoveField(
            model_name='alertdismissal',
            name='dismissed_at',
        ),
    ]
