# Generated by Django 6.1 on 2026-08-31 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_alertdismissal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporthistory',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='alertdismissal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alertdismissal',
            name='dismissed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='category',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('MEALS', 'Meals'), ('SUPPLIES', 'Supplies'), ('LODGING', 'Lodging'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='changed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
