# Generated by Django 6.1 on 2026-09-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_reporthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseline',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
