# Generated by Django 6.1 on 2026-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expenseline_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('APPROVER', 'Approver')], default='EMPLOYEE', max_length=20),
        ),
    ]
